<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="1" failed="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Failed suite [Default suite]" duration-ms="63" started-at="2019-01-12T15:40:25Z" finished-at="2019-01-12T15:40:25Z">
    <groups>
    </groups>
    <test name="Default test(failed)" duration-ms="63" started-at="2019-01-12T15:40:25Z" finished-at="2019-01-12T15:40:25Z">
      <class name="generic.sampletest">
        <test-method status="FAIL" signature="confBM()[pri:0, instance:generic.sampletest@224edc67]" name="confBM" is-config="true" duration-ms="0" started-at="2019-01-12T21:10:25Z" finished-at="2019-01-12T21:10:25Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at com.actitime.genericlib.Baseclass.confBM(Baseclass.java:18)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:510)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:211)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:585)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- confBM -->
        <test-method status="SKIP" signature="create()[pri:0, instance:generic.sampletest@224edc67]" name="create" duration-ms="16" started-at="2019-01-12T21:10:25Z" finished-at="2019-01-12T21:10:25Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- create -->
        <test-method status="SKIP" signature="confAM()[pri:0, instance:generic.sampletest@224edc67]" name="confAM" is-config="true" duration-ms="0" started-at="2019-01-12T21:10:25Z" finished-at="2019-01-12T21:10:25Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- confAM -->
      </class> <!-- generic.sampletest -->
    </test> <!-- Default test(failed) -->
  </suite> <!-- Failed suite [Default suite] -->
</testng-results>
